version: "3.8"
services:
  web:
    image: ghcr.io/hoarder-app/hoarder:release
    restart: unless-stopped
    volumes:
      - ./data:/data  #数据持久化
    ports:
      - 3298:3000
    environment:
      MEILI_ADDR: http://meilisearch:7700
      MEILI_MASTER_KEY: temp1234 # meilisearch全文引擎的访问秘钥，与下面要一致
      BROWSER_WEB_URL: http://chrome:9222
      NEXTAUTH_SECRET: super_random_string #为了安全，必须设置随机字符串
      NEXTAUTH_URL: http://localhost:3000
      DATA_DIR: /data
      #DISABLE_SIGNUPS: true #当你注册完第一个账户后，不再开放注册，可以开启这个禁用注册
      #OPENAI_API_KEY: sk-xxx #当需要自动为内容生成标签时，需要设置AI模型
      #OPENAI_BASE_URL: https://api.openai.com/v1
      #INFERENCE_TEXT_MODEL: gpt-4o  #文本处理模型，生成标签、摘要
      #INFERENCE_IMAGE_MODEL: grok-2-vision
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
  meilisearch:
    image: getmeili/meilisearch:v1.13.3
    restart: unless-stopped
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: temp1234 # meilisearch全文引擎的访问秘钥，请修改为难以破解的密码
    volumes:
      - ./meilisearch:/meili_data #全文索引数据持久化