services:
  liteportal:
    image: ghcr.io/cocolight/liteportal:latest
    container_name: liteportal
    restart: always
    ports:
      - "8080:8080"           # 宿主机:容器
    volumes:
      - ./data:/app/data      # 数据库持久化
    environment:
      PORT: 8080
      MAX_BODY_SIZE: 10mb
      LOG_LEVEL: info
      INIT_DATA: "true"