services:
  homarr:
    container_name: homarr  # 容器名称设置为 homarr
    image: ghcr.io/homarr-labs/homarr:latest  # 使用 homarr 镜像
    restart: unless-stopped  # 如果容器停止，除非手动停止，否则自动重启
    volumes:
      - ./var/run/docker.sock:/var/run/docker.sock # 可选，如果需要 Docker 集成，则挂载 Docker 套接字
      - ./homarr/appdata:/appdata  # 持久化数据存储，挂载到容器的 /appdata
    environment:
      - SECRET_ENCRYPTION_KEY=0fba08c349a19430bc822633f51899933edabc6d819bd82222ec01619e805c51    # 设置加密密钥
    ports:
      - '7575:7575'  # 将容器的 7575 端口映射到主机的 7575 端口