services:
  solara-music:
    image: ghcr.io/panda-995/solara-music:latest
    container_name: solara-music
    restart: unless-stopped
    ports:
      - "9696:3001"
    environment:
      - NODE_ENV=production      # 运行环境（注意不要有空格）
      - PORT=3001                # 应用监听端口（与上面一致）
    volumes:
      - ./logs:/app/logs