services
  netease-music
    image xmzd666netease_url_for_nas1.0
    container_name netease-music
    environment
      - COOKIE_FILE=datacookie.txt
      - AUTOREMOVE=true # 启用自动删除功能
      - AUTO_DELETE_TIME=60 # 60分钟清理间隔
      - WEBDL=true # 启用Web下载推送
    volumes
      - .cookie.txtdatacookie.txtro #cookie文件
      - .downloadsappdownloads # 永久下载目录
      - .tempapptemp # 临时下载目录
    ports
      - 150005000
    restart always