services:
    wechat-selkies:
        image: nickrunning/wechat-selkies:latest
        container_name: wechat-selkies
        stdin_open: true
        tty: true
        ports:
            - 3000:3000
            - 3001:3001
        restart: always
        volumes:
            - ./config:/config
        devices:
            - /dev/dri:/dev/dri
        environment:
            - PUID=1000                    # user ID
            - PGID=100                     # group ID
            - TZ=Asia/Shanghai             # timezone
            - LC_ALL=zh_CN.UTF-8           # locale
            - AUTO_START_WECHAT=true       # default is true  是否自动启动微信客户端
            - AUTO_START_QQ=false          # default is false 是否自动启动 QQ 客户端
            - CUSTOM_USER=<Your Name>      # 建议设置自定义用户名
            - PASSWORD=<Your Password>     # 建议为网页界面设置密码