version: '3.1'

services:
  redis:
    image: redis:7-alpine
    container_name: yyets-redis
    restart: always

  mongo:
    image: mongo:6
    container_name: yyets-mongo
    volumes:
      - ./mongo:/data/db
    command: --quiet

  meili:
    image: getmeili/meilisearch:v1.0.2
    environment:
      - MEILI_HTTP_PAYLOAD_SIZE_LIMIT=1073741824
    volumes:
      - ./meilisearch:/meili_data

  mysql:
    image: ubuntu/mysql:8.0-22.04_beta
    volumes:  
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    command: "--skip-log-bin --default-authentication-plugin=mysql_native_password"

  bot:
    image: bennythink/yyetsbot
    env_file: yyets.env
    depends_on:
      - redis
      - mongo

  web:
    image: bennythink/yyetsbot
    env_file: yyets.env
    ports:
      - "8877:8888"
    volumes:
      - ./subtitle:/YYeTsBot/yyetsweb/subtitle_data
    command: [ "python3","server.py","-h=0.0.0.0" ]