services:
  foxel:  # 定义服务名称
    image: ghcr.io/drizzletime/foxel:latest  # 使用的镜像，来自 GitHub 容器仓库（latest 表示最新版本）
    container_name: foxel  # 容器的自定义名称
    restart: always  # 自动重启策略：无论容器如何退出都会自动重启
    ports:
      - 8558:80  # 左边是宿主机端口(可自定义)：右边是容器端口(固定)
    environment:  # 环境变量配置
      - TZ=Asia/Shanghai  # 设置容器时区为上海
      - SECRET_KEY=Pq4Rz8XOk2aUwVnHe3xdHtMfK7oGiBcQ0vYsEhLkT1=  # 应用主密钥，用于加密操作（请更换为随机安全值）
      - TEMP_LINK_SECRET_KEY=vDDe-_NeZUsF1tcyAe8cziC8gKfwJnhfO0h6lOUktLA=  # 临时链接加密密钥，建议与主密钥不同
    volumes:  # 数据卷挂载配置
      - ./data:/app/data  # 左边是宿主机数据目录(可自定义)：右边是容器数据目录(固定)