version: '3.8'
services:
  quarkdrive-webdav:
    image: ghcr.io/chenqimiao/quarkdrive-webdav:latest
    container_name: quarkdrive-webdav
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - QUARK_COOKIE=you quark cookie
      - WEBDAV_AUTH_USER=admin
      - WEBDAV_AUTH_PASSWORD=admin