services:
  chfs:  # 定义服务名称
    image: docblue/chfs:v4.0beta.min  # 使用的镜像，来自 Docker Hub，版本为 v4.0beta.min
    container_name: chfs  # 容器的自定义名称
    restart: always  # 自动重启策略：容器退出时自动重启
    ports:
      - 6688:80  # 左边是宿主机端口(可自定义):右边是容器端口(固定)，用于访问 Web 文件服务
    volumes:  # 数据卷挂载配置
      - ./data:/data     # 左边是宿主机数据目录(可自定义):右边是容器数据目录(固定)，用于存放文件内容
      - ./config:/config # 左边是宿主机配置目录(可自定义):右边是容器配置目录(固定)，用于保存服务配置