services:
  picsur:
    image: ghcr.io/caramelfur/picsur:latest
    container_name: picsur
    restart: unless-stopped
    ports:
      - '8455:8080'
    environment:
      PICSUR_HOST: '0.0.0.0'
      PICSUR_PORT: 8080
      PICSUR_DB_HOST: picsur_postgres
      PICSUR_DB_PORT: 5432
      PICSUR_DB_USERNAME: picsur
      PICSUR_DB_PASSWORD: picsur
      PICSUR_DB_DATABASE: picsur
      PICSUR_ADMIN_PASSWORD: your_strong_password # 务必修改!!
      PICSUR_MAX_FILE_SIZE: 128000000 # 最大支持128MB文件

  picsur_postgres:
    image: postgres:14-alpine
    container_name: picsur_postgres
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: picsur
      POSTGRES_PASSWORD: picsur
      POSTGRES_USER: picsur