services:
  homehub:
    image: ghcr.io/surajverma/homehub:latest
    container_name: homehub
    ports:
      - "5552:5000" # 项目Web页面端口
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=gXKMHkqLBIQVImayQXAVWdzGBPuFJKggzcgvgPJPXpW
    volumes:
      - ./uploads:/app/uploads
      - ./media:/app/media
      - ./pdfs:/app/pdfs
      - ./data:/app/data
      - ./config.yml:/app/config.yml:ro
    restart: unless-stopped