services:
  linkstack:
    hostname: linkstack
    image: linkstackorg/linkstack:latest
    ports:
      - '8189:80'
      - '8190:443'
    environment:
      TZ: 'Asia/Shanghai'
      SERVER_ADMIN: 'admin@example.com'
      HTTP_SERVER_NAME: 'example.com'
      HTTPS_SERVER_NAME: 'example.com'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    volumes:
      - 'linkstack_data:/htdocs'
    restart: always

volumes:
  linkstack_data: