version: '3.8'
services:
  filegator:
    image: filegator/filegator:latest
    container_name: filegator
    restart: always
    ports:
      - 8880:8080
    volumes:
      - ./filegator/data:/var/www/filegator/repository/