version: '3.8'

services:
  stream-vault:
    image: qingfeng2336/stream-vault            # 使用的镜像
    container_name: stream-vault                # 容器名称
    restart: unless-stopped                      # 自动重启策略（可根据需要添加）
    ports:
      - "28083:28081"                            # 端口映射 主机:容器
    volumes:
      - "d:/home/spirit:/app"                   # 数据卷挂载 主机目录:容器目录
      - "d:/home/spirit/tmp:/tmp"               # 数据卷挂载 主机目录:容器目录