version: '3.8'

services:
  cloudt:
    image: jpillora/cloud-torrent      # 镜像名称
    container_name: cloudt             # 容器名称
    restart: always                    # 自动重启策略
    ports:
      - "3000:3000"                    # HTTP 端口映射
    volumes:
      - ./downloads:/downloads  # 下载目录挂载
    command: ["--auth", "admin:admin123"]               # 启动参数，设置账号密码
    environment:
      # 可选环境变量，如时区等
      # - TZ=Asia/Shanghai