version: '3.8'

services:
  vlmcsd:
    image: mikolatero/vlmcsd   # 镜像名称
    container_name: vlmcsd     # 容器名称
    restart: always            # 自动重启策略
    ports:
      - "1688:1688"            # KMS 默认端口映射
    volumes:
      - /home/docker/vlmcsd/data:/data   # 持久化数据卷，可保存日志或配置
    environment:
      # 如果镜像支持环境变量，可在这里添加
      # - TZ=Asia/Shanghai      # 设置时区，例如上海