services:
  playlistdl:
    image: tanner23456/playlistdl:v2
    container_name: playlistdl
    ports:
      - "4827:5000"
    restart: always  # 始终自动重启容器    
    environment:
      ADMIN_USERNAME: "admin"  # 管理员用户名
      ADMIN_PASSWORD: "admin"  # 管理员密码
      AUDIO_DOWNLOAD_PATH: "/data"  # 音频下载保存路径
      CLEANUP_INTERVAL: "300"  # 自动清理音频的时间间隔（单位：秒）
    volumes:
      - ./data:/data  # Reference env variable here as well