services:
  wdhyfzqsrj:
    container_name: wdhyfzqsrj
    image: swr.cn-north-4.myhuaweicloud.com/firfe/wdhyfzqsrj:1.0.8.7
    network_mode: bridge
    restart: always
    logging:
      options:
        max-size: 1m
        max-file: '1'
    ports:
      - 5151:5151