services:
  nullbr115:
    image: gravityle/nullbr115:latest
    container_name: nullbr115
    ports:
      - 8115:8115
    volumes:
      - ./nullbr115/config:/config
      - ./nullbr115/media:/media
    environment:
      - API_KEY=‘XXXXX’
    restart: always