services:
  cube-city:
    container_name: cube-city
    image: swr.cn-north-4.myhuaweicloud.com/firfe/cube-city:2025.09.10
    network_mode: bridge
    restart: always
    logging:
      options:
        max-size: 1m
        max-file: '1'
    ports:
      - 5141:5141