services:
  mediamaster:
    image: docker.1ms.run/smysong/mediamaster-v2:latest
    container_name: mediamaster
    environment:
      - UID=1000
      - GID=100
      - GIDLIST=100
      - TZ=Asia/Shanghai #设置中国时区
    volumes:
      # - /share/Container/Torrent:/Torrent
      # 上面这个是针对非qb、tr、迅雷的其它下载的种子监听
      - .Mediamaster/Downloads:/Downloads
      - /share/Container/Mediamaster:/config
      - /share/Media:/Media
    ports:
      - 8888:8888
    restart: always