services:
  feishin:
    container_name: feishin              # 容器名称
    image: ghcr.io/jeffvli/feishin:latest  # Feishin 镜像（支持 Jellyfin/Navidrome）
    environment:
      - SERVER_NAME=navidrome             # 预定义的服务器名称（可自定义）
      - SERVER_LOCK=true                 # 如果为 true，且设置了 name/type/url，则用户只能输入账号密码
      - SERVER_TYPE=navidrome             # 服务器类型：jellyfin 或 navidrome
      - SERVER_URL=   # 你的 Jellyfin 、Navidrome地址（示例）
      - PUID=1000                        # 宿主机用户 ID，保持一致可避免权限问题
      - PGID=1000                        # 宿主机用户组 ID
      - UMASK=002                        # 文件权限掩码，002 表示 775/664
      - TZ=Asia/Shanghai                 # 时区（改成你所在的时区）
    ports:
      - "9180:9180"                      # 映射端口：宿主机 9180 → 容器 9180
    restart: always                      # 容器异常/重启后总是自动启动