version: '3'
services:
  mikochi:
    image: zer0tonin/mikochi:latest
    container_name: mikochi
    restart: unless-stopped
    ports:
      - 8044:8080
    volumes:
      - ./data:/data
    environment:
      - DATA_DIR=/data
      - USERNAME=admin
      - PASSWORD=admin